[tool.ruff]
target-version = "py39"
line-length = 120
indent-width = 4
exclude = [
    "versions",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "fmlib",
    "cybernationVenv"
]

[tool.ruff.lint]
select = ["E", "F", "I", "C"]
ignore = []
extend-ignore = [
    "E711",
    "E731",
    "E501", # TODO: remove E501 after fixing all the long lines
    "C901" # TODO: Enable this after fixing all the long functions
]

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

skip-magic-trailing-comma = false

line-ending = "auto"
