[default]
SERVICE_NAME="alchemiser"
DEBUG= true
CORS_ORIGIN = ["*"]

[dev]
DB_HOST = "localhost"
DB_USER = "flask"
DB_PASSWORD = "flask"
DB_NAME = "alchemiserdb"
DB_PORT = 5435

[test]

[stage]

[prod]
